INSERT INTO role(role) VALUES ('ADMIN');
INSERT INTO role(role) VALUES ('COUNCILMAN');
INSERT INTO councilman (first_name, last_name, committee, description, email, password, role_id) VALUES ('Tomasz', 'Tomalski', 'Oświaty', 'Radny 1 kadencji', 'tomasz@tomasz', 'haslo1', 2);
INSERT INTO councilman (first_name, last_name, committee, description, email, password, role_id) VALUES ('Bartosz', 'Bartoszczyk', 'Budżetu', 'Radny 8 kadencji', 'bartosz@bartosz.pl', 'haslo2', 2);
INSERT INTO super_admin(email, password) VALUES ('admin@gmina.pl', 'haslo3');
INSERT INTO interpellation(title, description, date, councilman_id) VALUES ('Droga', 'Proszę o załatanie dziur w drodze gminnej. Kałuże jak cholera', '2020-11-11', 1);
INSERT INTO interpellation(title, description, date, councilman_id) VALUES ('Śmieci', 'Proszę uprzątnąć dzikie wysypisko', '2020-11-11', 1);
INSERT INTO interpellation(title, description, date, councilman_id) VALUES ('Plac zabaw', 'Proszę o ujęcie w planie budżetu budowę placu zabaw w miejscowości Budziwojów', '2020-11-11', 2);
INSERT INTO sessionelem(name) VALUES ('Otwarcie sesji i stwierdzenie jej prawomocności');
INSERT INTO sessionelem(name) VALUES ('Przyjęcie porządku obrad');
INSERT INTO sessionelem(name) VALUES ('Sprawozdanie Wójta z działalnosci między sesyjnej');
INSERT INTO sessionelem(name) VALUES ('Interpelacje i zapytania');
INSERT INTO sessionelem(name) VALUES ('Wolne wnioski');
INSERT INTO sessionelem(name) VALUES ('Przyjęcie protokołów');
INSERT INTO sessionelem(name) VALUES ('Sprawy różne');
INSERT INTO sessionelem(name) VALUES ('Zamknięcie obrad');
INSERT INTO session_order(number, date, time) VALUES ('I', '2020-05-10', '12:00');
INSERT INTO session_order(number, date, time) VALUES ('II', '2020-06-10', '13:00');
INSERT INTO session_order(number, date, time) VALUES ('III', '2020-07-18', '14:00');
INSERT INTO session_order(number, date, time) VALUES ('IV', '2020-10-11', '16:00');
INSERT INTO order_elements(order_id, elem_id) VALUES (1, 1);